FROM registry.access.redhat.com/ubi8@sha256:3e3e4e91c8ddfb6e5f8e43e0f4e5eb857e9511f3e375cd513fb88e69f7e181d8
LABEL org.opencontainers.image.title="base-ubi8" \
      org.opencontainers.image.maintainer="Ryan Craig <ryan.craig@infrashift.io>" \
      org.opencontainers.image.version="2025.04.02" \
      org.opencontainers.image.description="UBI8 base image for secure development" \
      io.infrashift.image.signing-oidc-issuer="https://token.actions.githubusercontent.com" \
      io.infrashift.image.source-registry="ghcr.io/infrashift/base-ubi-images" \
      io.infrashift.image.source-repo="https://github.com/infrashift/base-ubi-images" \
      io.openshift.tags="ubi8,base" \
      io.openshift.expose-services=""
RUN microdnf update -y && microdnf clean all
RUN useradd -u 1001 -g 0 -m -d /workspace user
USER 1001:0
WORKDIR /workspace
CMD ["bash"]