FROM registry.access.redhat.com/ubi9@sha256:9a8dd2a9f595f9908f2e4560a6e6e510d3c22e0d465fa5fb167108e5c2b2e546
LABEL org.opencontainers.image.title="base-ubi9" \
      org.opencontainers.image.maintainer="Ryan Craig <ryan.craig@infrashift.io>" \
      org.opencontainers.image.version="2025.04.02" \
      org.opencontainers.image.description="UBI9 base image for secure development" \
      io.infrashift.image.signing-oidc-issuer="https://token.actions.githubusercontent.com" \
      io.infrashift.image.source-registry="ghcr.io/infrashift/base-ubi-images" \
      io.infrashift.image.source-repo="https://github.com/infrashift/base-ubi-images" \
      io.openshift.tags="ubi9,base" \
      io.openshift.expose-services=""
RUN microdnf update -y && microdnf clean all
RUN useradd -u 1001 -g 0 -m -d /workspace user
USER 1001:0
WORKDIR /workspace
CMD ["bash"]